/** Defense in depth, not yet a proven native-tool allowlist. See the experiment gate. */
export const CODEX_EXPERIMENT_CONFIG: Record<string, unknown> = {
  approval_policy: 'on-request',
  sandbox_mode: 'read-only',
  web_search: 'disabled',
  cli_auth_credentials_store: 'keyring',
  forced_login_method: 'chatgpt',
  project_doc_max_bytes: 0,
  check_for_update_on_startup: false,
  'history.persistence': 'none',
  'analytics.enabled': false,
  'feedback.enabled': false,
  'agents.enabled': false,
  'features.shell_tool': false,
  'features.unified_exec': false,
  'features.shell_snapshot': false,
  'features.view_image': false,
  'tools.view_image': false,
  'features.apps': false,
  'features.plugins': false,
  'features.remote_plugin': false,
  'features.hooks': false,
  'features.browser_use': false,
  'features.browser_use_external': false,
  'features.computer_use': false,
  'features.in_app_browser': false,
  'features.multi_agent': false,
  'features.multi_agent_v2': false,
  'features.memories': false,
  'features.workspace_dependencies': false,
  'features.skill_mcp_dependency_install': false,
  'features.skip_host_skill_discovery': true,
  'features.skill_search': false,
  'features.code_mode': false,
  'features.code_mode_host': false,
  'features.image_generation': false,
  'features.goals': false,
  'features.sleep_tool': false,
  'features.tool_suggest': false,
};

export function codexConfigArgs(config: Record<string, unknown>): string[] {
  return Object.entries(config).flatMap(([key, value]) => ['-c', `${key}=${JSON.stringify(value)}`]);
}
